// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyntheticService provides methods callable from the Svelte frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2671238860);
}

/**
 * @param {string} simulationType
 * @param {number} numPoints
 * @param {number} numSeries
 * @param {number} noise
 * @param {number} correlationTime
 * @param {number} amplitude
 * @param {number} frequency
 * @returns {$CancellablePromise<void>}
 */
export function Submit(simulationType, numPoints, numSeries, noise, correlationTime, amplitude, frequency) {
    return $Call.ByID(2296039174, simulationType, numPoints, numSeries, noise, correlationTime, amplitude, frequency);
}
